name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
permissions:
  contents: write
on: [push]
jobs:
  test-codespace:
    runs-on: ubuntu-22.04
    env:
      RepositoryName: "codespaces-synchronizer"
      DT_TENANT: ${{ secrets.DT_TENANT }}
      DT_OPERATOR_TOKEN: ${{ secrets.DT_OPERATOR_TOKEN }}
      DT_INGEST_TOKEN: ${{ secrets.DT_INGEST_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test Codespace (devcontainer) build and run commands
        uses: devcontainers/ci@v0.3
        with:
          runCmd: ./scripts/test.sh
        env:
          RepositoryName: "codespaces-synchronizer"
          DT_TENANT: ${{ secrets.DT_TENANT }}
          DT_OPERATOR_TOKEN: ${{ secrets.DT_OPERATOR_TOKEN }}
          DT_INGEST_TOKEN: ${{ secrets.DT_INGEST_TOKEN }}
        
